//! Strings builtin registry slice.

use super::core;
use crate::builtins::{BuiltinCompatibility, BuiltinEntry};

pub(in crate::builtins) const ENTRIES: &[BuiltinEntry] = &[
    BuiltinEntry::new(
        "base64_decode",
        core::builtin_base64_decode,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "base64_encode",
        core::builtin_base64_encode,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new("bin2hex", core::builtin_bin2hex, BuiltinCompatibility::Php),
    BuiltinEntry::new("chr", core::builtin_chr, BuiltinCompatibility::Php),
    BuiltinEntry::new(
        "addslashes",
        core::builtin_addslashes,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "convert_uudecode",
        core::builtin_convert_uudecode,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "convert_uuencode",
        core::builtin_convert_uuencode,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new("crc32", core::builtin_crc32, BuiltinCompatibility::Php),
    BuiltinEntry::new("explode", core::builtin_explode, BuiltinCompatibility::Php),
    BuiltinEntry::new("hash", core::builtin_hash, BuiltinCompatibility::Php),
    BuiltinEntry::new(
        "hash_hmac",
        core::builtin_hash_hmac,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new("hex2bin", core::builtin_hex2bin, BuiltinCompatibility::Php),
    BuiltinEntry::new(
        "htmlentities",
        core::builtin_htmlentities,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "htmlspecialchars",
        core::builtin_htmlspecialchars,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "htmlspecialchars_decode",
        core::builtin_htmlspecialchars_decode,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "http_build_query",
        core::builtin_http_build_query,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new("implode", core::builtin_implode, BuiltinCompatibility::Php),
    BuiltinEntry::new("lcfirst", core::builtin_lcfirst, BuiltinCompatibility::Php),
    BuiltinEntry::new("ltrim", core::builtin_ltrim, BuiltinCompatibility::Php),
    BuiltinEntry::new("md5", core::builtin_md5, BuiltinCompatibility::Php),
    BuiltinEntry::new("ord", core::builtin_ord, BuiltinCompatibility::Php),
    BuiltinEntry::new("pack", core::builtin_pack, BuiltinCompatibility::Php),
    BuiltinEntry::new(
        "parse_url",
        core::builtin_parse_url,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new("printf", core::builtin_printf, BuiltinCompatibility::Php),
    BuiltinEntry::new(
        "rawurldecode",
        core::builtin_rawurldecode,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "rawurlencode",
        core::builtin_rawurlencode,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new("rtrim", core::builtin_rtrim, BuiltinCompatibility::Php),
    BuiltinEntry::new("sha1", core::builtin_sha1, BuiltinCompatibility::Php),
    BuiltinEntry::new("sprintf", core::builtin_sprintf, BuiltinCompatibility::Php),
    BuiltinEntry::new(
        "str_contains",
        core::builtin_str_contains,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "str_ends_with",
        core::builtin_str_ends_with,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new("str_pad", core::builtin_str_pad, BuiltinCompatibility::Php),
    BuiltinEntry::new(
        "str_repeat",
        core::builtin_str_repeat,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "str_replace",
        core::builtin_str_replace,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "str_starts_with",
        core::builtin_str_starts_with,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "strcasecmp",
        core::builtin_strcasecmp,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new("strcmp", core::builtin_strcmp, BuiltinCompatibility::Php),
    BuiltinEntry::new("strcspn", core::builtin_strcspn, BuiltinCompatibility::Php),
    BuiltinEntry::new("stripos", core::builtin_stripos, BuiltinCompatibility::Php),
    BuiltinEntry::new(
        "strip_tags",
        core::builtin_strip_tags,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "stripcslashes",
        core::builtin_stripcslashes,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "stripslashes",
        core::builtin_stripslashes,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new("stristr", core::builtin_stristr, BuiltinCompatibility::Php),
    BuiltinEntry::new("strlen", core::builtin_strlen, BuiltinCompatibility::Php),
    BuiltinEntry::new(
        "strnatcasecmp",
        core::builtin_strnatcasecmp,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "strnatcmp",
        core::builtin_strnatcmp,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "strncasecmp",
        core::builtin_strncasecmp,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new("strncmp", core::builtin_strncmp, BuiltinCompatibility::Php),
    BuiltinEntry::new(
        "quotemeta",
        core::builtin_quotemeta,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new("strpbrk", core::builtin_strpbrk, BuiltinCompatibility::Php),
    BuiltinEntry::new("strpos", core::builtin_strpos, BuiltinCompatibility::Php),
    BuiltinEntry::new("strrev", core::builtin_strrev, BuiltinCompatibility::Php),
    BuiltinEntry::new("strrchr", core::builtin_strrchr, BuiltinCompatibility::Php),
    BuiltinEntry::new(
        "strripos",
        core::builtin_strripos,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new("strrpos", core::builtin_strrpos, BuiltinCompatibility::Php),
    BuiltinEntry::new("strspn", core::builtin_strspn, BuiltinCompatibility::Php),
    BuiltinEntry::new("strstr", core::builtin_strstr, BuiltinCompatibility::Php),
    BuiltinEntry::new("strtok", core::builtin_strtok, BuiltinCompatibility::Php),
    BuiltinEntry::new(
        "strtolower",
        core::builtin_strtolower,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "strtoupper",
        core::builtin_strtoupper,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new("strtr", core::builtin_strtr, BuiltinCompatibility::Php),
    BuiltinEntry::new("strval", core::builtin_strval, BuiltinCompatibility::Php),
    BuiltinEntry::new(
        "substr_compare",
        core::builtin_substr_compare,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "substr_count",
        core::builtin_substr_count,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "substr_replace",
        core::builtin_substr_replace,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new("trim", core::builtin_trim, BuiltinCompatibility::Php),
    BuiltinEntry::new("ucfirst", core::builtin_ucfirst, BuiltinCompatibility::Php),
    BuiltinEntry::new("ucwords", core::builtin_ucwords, BuiltinCompatibility::Php),
    BuiltinEntry::new("unpack", core::builtin_unpack, BuiltinCompatibility::Php),
    BuiltinEntry::new(
        "urldecode",
        core::builtin_urldecode,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "urlencode",
        core::builtin_urlencode,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "version_compare",
        core::builtin_version_compare,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new("vprintf", core::builtin_vprintf, BuiltinCompatibility::Php),
    BuiltinEntry::new(
        "vsprintf",
        core::builtin_vsprintf,
        BuiltinCompatibility::Php,
    ),
    BuiltinEntry::new(
        "wordwrap",
        core::builtin_wordwrap,
        BuiltinCompatibility::Php,
    ),
];
