#!/usr/bin/env python3
"""Generate deterministic Rust arginfo metadata from php-src stub files."""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass, replace
from pathlib import Path


FUNCTION_RE = re.compile(
    r"function\s+([A-Za-z_\\][A-Za-z0-9_\\]*)\s*\((.*?)\)\s*(?::\s*([^;{]+))?[;{]",
    re.DOTALL,
)
PARAM_RE = re.compile(
    r"(?P<byref>&)?\s*(?P<variadic>\.\.\.)?\s*\$(?P<name>[A-Za-z_][A-Za-z0-9_]*)"
)


@dataclass(frozen=True)
class FunctionArginfo:
    name: str
    required: int
    total: int
    by_ref: tuple[str, ...]
    variadic: bool
    return_type: str
    source: str


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--php-src", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--overrides", type=Path)
    args = parser.parse_args()

    try:
        functions = collect_functions(args.php_src)
        if args.overrides:
            functions = apply_overrides(functions, args.overrides)
        write_rust(args.out, functions)
    except Exception as error:  # noqa: BLE001 - script boundary.
        print(f"phase6 arginfo generation error: {error}", file=sys.stderr)
        return 1
    print(f"[ok] wrote {args.out}")
    return 0


def collect_functions(php_src: Path) -> list[FunctionArginfo]:
    if not php_src.exists():
        raise FileNotFoundError(f"php-src path does not exist: {php_src}")
    functions: dict[str, FunctionArginfo] = {}
    for stub in sorted(php_src.rglob("*.stub.php")):
        text = strip_comments(stub.read_text(encoding="utf-8"))
        relative = stub.relative_to(php_src).as_posix()
        for match in FUNCTION_RE.finditer(text):
            name = match.group(1).split("\\")[-1]
            params = parse_params(match.group(2))
            functions[name.lower()] = FunctionArginfo(
                name=name,
                required=sum(1 for param in params if not param["optional"]),
                total=len(params),
                by_ref=tuple(param["name"] for param in params if param["by_ref"]),
                variadic=any(param["variadic"] for param in params),
                return_type=normalize_type(match.group(3) or "mixed"),
                source=relative,
            )
    return [functions[key] for key in sorted(functions)]


def strip_comments(text: str) -> str:
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.DOTALL)
    return re.sub(r"//.*", "", text)


def parse_params(raw: str) -> list[dict[str, object]]:
    if not raw.strip():
        return []
    params = []
    for chunk in split_params(raw):
        match = PARAM_RE.search(chunk)
        if match:
            params.append(
                {
                    "name": match.group("name"),
                    "optional": "=" in chunk,
                    "by_ref": bool(match.group("byref")),
                    "variadic": bool(match.group("variadic")),
                }
            )
    return params


def split_params(raw: str) -> list[str]:
    params: list[str] = []
    depth = 0
    start = 0
    for index, char in enumerate(raw):
        if char in "([{":
            depth += 1
        elif char in ")]}":
            depth = max(0, depth - 1)
        elif char == "," and depth == 0:
            params.append(raw[start:index].strip())
            start = index + 1
    tail = raw[start:].strip()
    if tail:
        params.append(tail)
    return params


def normalize_type(raw: str) -> str:
    return " ".join(raw.strip().split()).replace(" | ", "|")


def apply_overrides(
    functions: list[FunctionArginfo], overrides_path: Path
) -> list[FunctionArginfo]:
    by_name = {function.name.lower(): function for function in functions}
    for line_number, raw in enumerate(overrides_path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        parts = dict(part.split("=", 1) for part in line.split() if "=" in part)
        name = parts.get("name", "").lower()
        if name not in by_name:
            raise ValueError(f"{overrides_path}:{line_number}: unknown function {name!r}")
        function = by_name[name]
        if "return" in parts:
            function = replace(function, return_type=parts["return"])
        if "required" in parts:
            function = replace(function, required=int(parts["required"]))
        by_name[name] = function
    return [by_name[key] for key in sorted(by_name)]


def write_rust(path: Path, functions: list[FunctionArginfo]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "// @generated by scripts/phase6/generate_arginfo.py",
        "// Source: php-src *.stub.php metadata for PHP 8.5.7.",
        "// Attribution: derived from php-src stub declarations; no C code is executed.",
        "",
        "#[derive(Clone, Copy, Debug, Eq, PartialEq)]",
        "pub struct GeneratedArginfo {",
        "    pub name: &'static str,",
        "    pub required: usize,",
        "    pub total: usize,",
        "    pub by_ref: &'static [&'static str],",
        "    pub variadic: bool,",
        "    pub return_type: &'static str,",
        "    pub source: &'static str,",
        "}",
        "",
        "pub const GENERATED_ARGINFO: &[GeneratedArginfo] = &[",
    ]
    for function in functions:
        by_ref = ", ".join(f'"{name}"' for name in function.by_ref)
        lines.extend(
            [
                "    GeneratedArginfo {",
                f'        name: "{rust_escape(function.name)}",',
                f"        required: {function.required},",
                f"        total: {function.total},",
                f"        by_ref: &[{by_ref}],",
                f"        variadic: {str(function.variadic).lower()},",
                f'        return_type: "{rust_escape(function.return_type)}",',
                f'        source: "{rust_escape(function.source)}",',
                "    },",
            ]
        )
    lines.append("];")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def rust_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


if __name__ == "__main__":
    raise SystemExit(main())
